---
- name: raw result of running date command
  ansible.builtin.debug:
    msg: "{{ lookup('ansible.builtin.pipe', 'git log --format=\"last commit: %h\" -1') }}"

- name: Template file
  ansible.builtin.template:
    src: hello.sh.j2
    dest: "{{ ansible_env.HOME }}/hello.sh"
    mode: 0755
